/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiche;

import java.awt.Frame;

import javax.swing.ImageIcon;

import model.Sistema;

/**
 *
 * @author Tucaa
 */
public class principal2 extends javax.swing.JFrame {

    /**
     * Creates new form teste
     */
    public principal2() {
        initComponents();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setIconImage(new ImageIcon(getClass().getResource("/icone.png")).getImage());
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guiche Eletrônico™ - V. 0.0.1");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setBounds(new java.awt.Rectangle(350, 50, 1280, 960));
        setPreferredSize(new java.awt.Dimension(1280, 960));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 184, -1, -1));

        jTextField27.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField27.setEditable(false);
        jTextField27.setForeground(new java.awt.Color(153, 153, 153));
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField27.setToolTipText("");
       // jTextField27.setBorder(null);
        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 180, 90));

        jTextField28.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField28.setEditable(false);
        jTextField28.setForeground(new java.awt.Color(153, 153, 153));
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField28.setToolTipText("");
        //jTextField28.setBorder(null);
        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, 180, 90));

        jTextField11.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField11.setEditable(false);
        jTextField11.setForeground(new java.awt.Color(153, 153, 153));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
       // jTextField11.setToolTipText("");
       // jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 540, 180, 90));

        jTextField29.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField29.setEditable(false);
        jTextField29.setForeground(new java.awt.Color(153, 153, 153));
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField29.setToolTipText("");
        //jTextField29.setBorder(null);
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, 180, 90));

        jTextField31.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField31.setEditable(false);
        jTextField31.setForeground(new java.awt.Color(153, 153, 153));
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField31.setToolTipText("");
       // jTextField31.setBorder(null);
        jTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField31ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 180, 90));

        jTextField30.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField30.setEditable(false);
        jTextField30.setForeground(new java.awt.Color(153, 153, 153));
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField30.setToolTipText("");
       // jTextField30.setBorder(null);
        jTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField30ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 180, 90));

        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/chamar.png"))); // NOI18N
        jButton4.setToolTipText("Chamar Próximo");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 630, -1, 220));

        jTextField3.setFont(new java.awt.Font("Arial Black", 0, 90)); // NOI18N
        jTextField3.setEditable(false);
       // jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField3.setToolTipText("");
       // jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 640, 320, 150));
   
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/botao_p.png")));  // NOI18N
        jButton3.setToolTipText("Senha Prioritária");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, 160));
        

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/botao_c.png"))); // NOI18N
        jButton2.setToolTipText("Senha Comum");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 170, 160));
        
        jTextField10.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField10.setEditable(false);
        jTextField10.setForeground(new java.awt.Color(153, 153, 153));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField10.setToolTipText("");
      //  jTextField10.setBorder(null);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 180, 90));


        

        jTextField2.setFont(new java.awt.Font("Arial Black", 0, 90)); // NOI18N
        jTextField2.setEditable(false);
        //jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField2.setToolTipText("");
       // jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 295, 260, -1));

        jTextField23.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField23.setEditable(false);
        jTextField23.setForeground(new java.awt.Color(153, 153, 153));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField23.setToolTipText("");
        //jTextField23.setBorder(null);
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 180, 90));

        jTextField24.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField24.setEditable(false);
        jTextField24.setForeground(new java.awt.Color(153, 153, 153));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField24.setToolTipText("");
        //jTextField24.setBorder(null);
        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 180, 90));

        jTextField25.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField25.setEditable(false);
        jTextField25.setForeground(new java.awt.Color(153, 153, 153));
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField25.setToolTipText("");
        //jTextField25.setBorder(null);
        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 180, 90));

        jTextField22.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField22.setEditable(false);
        jTextField22.setForeground(new java.awt.Color(153, 153, 153));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField22.setToolTipText("");
        //jTextField22.setBorder(null);
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 180, 90));

        jTextField26.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jTextField26.setEditable(false);
        jTextField26.setForeground(new java.awt.Color(153, 153, 153));
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        //jTextField26.setToolTipText("");
        //jTextField26.setBorder(null);
        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 180, 90));
        

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/senhaschamadas.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/senhasgeradas.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 500, -1));


        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/baixo.png"))); // NOI18N
        //jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 860, 1280, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiche/images/cima.png"))); // NOI18N
        //jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));
        
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField31ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }          
    @SuppressWarnings("static-access")
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	Sistema.getInstance().chamarSenha();
        updateSenhasChamadas();
        ((guiche2) guiche).update();
    }    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Sistema.getInstance().gerarSenhaPrioritaria();
        updateSenhasGeradas();
    }          
    
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	Sistema.getInstance().gerarSenhaConvencional();
    	updateSenhasGeradas();
    }
    
    private void updateSenhasGeradas(){
    	jTextField2.setText(Sistema.getInstance().getSenhaGerada(0));
    	jTextField25.setText(Sistema.getInstance().getSenhaGerada(1));
    	jTextField26.setText(Sistema.getInstance().getSenhaGerada(2));
    	jTextField24.setText(Sistema.getInstance().getSenhaGerada(3));
    	jTextField22.setText(Sistema.getInstance().getSenhaGerada(4));
    	jTextField23.setText(Sistema.getInstance().getSenhaGerada(5));
    	jTextField10.setText(Sistema.getInstance().getSenhaGerada(6));
    }
    
    private void updateSenhasChamadas(){
    	jTextField3.setText(Sistema.getInstance().getSenhaChamada(0));
    	jTextField27.setText(Sistema.getInstance().getSenhaChamada(1));
    	jTextField30.setText(Sistema.getInstance().getSenhaChamada(2));
    	jTextField28.setText(Sistema.getInstance().getSenhaChamada(3));
    	jTextField31.setText(Sistema.getInstance().getSenhaChamada(4));
    	jTextField29.setText(Sistema.getInstance().getSenhaChamada(5));
    	jTextField11.setText(Sistema.getInstance().getSenhaChamada(6));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
            	guiche = new guiche2();
                new guiche2().setVisible(true);
                new principal2().setVisible(true);

            }
        });
        
        
        
    }
    // Variables declaration - do not modify                     
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;

    
    private static Frame guiche;
    // End of variables declaration                   
}
